import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import DirectoryPage from './DirectoryPage.js'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['400', '700'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BBB Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DirectoryPage />
    </>
  )
}